version: '3.1'

services:
  app:
      container_name: 'app'
      restart: always
      build:
        context: ./
      ports:
      - ${PORT}:${PORT}
      networks:
      - appNetwork
      volumes:
      - .:/app
      env_file:
      - .env
      depends_on:
      - postgres

  postgres:
    container_name: pg-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${POSTGRES_DATA}
    ports:
    - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - appNetwork
    volumes:
      - postgresVol:${POSTGRES_DATA}
networks:
    appNetwork:
      driver: bridge

volumes:
    postgresVol: